### PR TITLE
This is a definite fix

### PR DESCRIPTION
**Pull request by theotterlord**
Was about to add this to the last one, but you merged before I could do it 😆 

I just missed one character. 

Also, I did test this one 😆

### CODE REVIEW

**Comment by JortvD** [comment]
Oh, I might have been a bit quick with that merge indeed. I also think it might be better to return before trying to append to an undefined path, because you already know the path is undefined and it will optimize the function a bit.

**Comment by theotterlord** [comment]
Yeah, that helps a lot

**Comment by JortvD** [comment]
Do you think it'll work now? Then I'll setup some testing infrastructure.

**Comment by theotterlord** [comment]
Yeah, it works now. I've been using it on my local branch. Definitely time for testing 😄

**Pull request merged**
